## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ushuaia,AR,2022-07-13 15:29:26,-54.8000,-68.3000,37.06,75,75,13.80,broken clouds
1,1,Hobart,AU,2022-07-13 15:29:26,-42.8794,147.3294,37.27,94,21,9.22,few clouds
2,2,Kudahuvadhoo,MV,2022-07-13 15:29:28,2.6708,72.8944,83.01,73,9,11.50,clear sky
3,3,Bluff,NZ,2022-07-13 15:29:28,-46.6000,168.3333,42.80,79,100,15.66,overcast clouds
4,4,Mount Isa,AU,2022-07-13 15:29:28,-20.7333,139.5000,49.77,50,0,8.05,clear sky

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input('What is the minimum temperature you would like for your vacation?'))

max_temp = float(input('What is the maximum temperature you would like for your vacation?'))

What is the minimum temperature you would like for your vacation?65
What is the maximum temperature you would like for your vacation?90

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df=city_data_df.loc[(city_data_df['Max Temp'] <= max_temp) & (city_data_df['Max Temp'] >= min_temp)]

preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Kudahuvadhoo,MV,2022-07-13 15:29:28,2.6708,72.8944,83.01,73,9,11.50,clear sky
5,5,Vaitape,PF,2022-07-13 15:28:54,-16.5167,-151.7500,77.45,76,4,16.17,light rain
6,6,Yellowknife,CA,2022-07-13 15:25:03,62.4560,-114.3525,66.72,59,40,4.00,scattered clouds
7,7,Oriximina,BR,2022-07-13 15:29:29,-1.7656,-55.8661,85.80,65,80,3.76,broken clouds
11,11,Nong Khai,TH,2022-07-13 15:29:30,17.9167,103.0833,77.29,91,100,7.49,heavy intensity rain

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                3
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Kudahuvadhoo,MV,83.01,clear sky,2.6708,72.8944,
5,Vaitape,PF,77.45,light rain,-16.5167,-151.7500,
6,Yellowknife,CA,66.72,scattered clouds,62.4560,-114.3525,
7,Oriximina,BR,85.80,broken clouds,-1.7656,-55.8661,
11,Nong Khai,TH,77.29,heavy intensity rain,17.9167,103.0833,
12,Georgetown,MY,82.89,moderate rain,5.4112,100.3354,
14,Rikitea,PF,71.74,light rain,-23.1203,-134.9692,
16,Nikolskoye,RU,78.87,clear sky,59.7035,30.7861,
17,Saint-Philippe,RE,69.39,light rain,-21.3585,55.7679,
19,Mangit,UZ,87.62,few clouds,40.5971,70.9607,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat=row["Lat"]
    
    lng=row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search.
    hotels=requests.get(base_url,params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index,"Hotel Name"]=hotels["results"][0]["name"]
        print("Hotel found")
        
    except:
        print("Hotel not found ... skipping")

Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found ... skipping
Hotel found
Hotel found
Hotel not found ... skipping
Hotel not found ... skipping
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found

In [11]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df=hotel_df.dropna()

clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Kudahuvadhoo,MV,83.01,clear sky,2.6708,72.8944,Niyama Private Islands Maldives
5,Vaitape,PF,77.45,light rain,-16.5167,-151.7500,Conrad Bora Bora Nui
6,Yellowknife,CA,66.72,scattered clouds,62.4560,-114.3525,The Explorer Hotel
7,Oriximina,BR,85.80,broken clouds,-1.7656,-55.8661,Pousada Tia Amélia
11,Nong Khai,TH,77.29,heavy intensity rain,17.9167,103.0833,จารุวรรณ วงชัยยา

In [12]:
# 8a. Create the output File (CSV)
output_data_file='../Vacation_Search/WeatherPy_vacation.csv'

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [13]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description} °F</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map. 
locations=clean_hotel_df[['Lat','Lng']]

city_description = clean_hotel_df['Current Description']

fig=gmaps.figure(center=(30.0,31.0), zoom_level=1.5)

marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))